; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32-s3-devkitc-1]
; [env:freenove_esp32_s3_wroom]   ; https://docs.platformio.org/en/latest/boards/espressif32/freenove_esp32_s3_wroom.html#board-espressif32-freenove-esp32-s3-wroom
platform = espressif32 @ 6.10.0
board = esp32-s3-devkitc-1 ;freenove_esp32_s3_wroom
framework = arduino
platform_packages=
;     framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#idf-release/v3.1.3
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.1.2
    platformio/framework-espidf @ https://github.com/espressif/esp-idf.git#v5.3    ;file:///home/shaun/my_repos/esp-idf

; build_flags =
;    -DARDUINO_USB_MODE=1
;    -DARDUINO_USB_CDC_ON_BOOT=1

;/dev/ttyCH343USB0
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
; monitor_rts = 0
; monitor_dtr = 0