; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32-s3-devkitc-1]
; [env:freenove_esp32_s3_wroom]   ; https://docs.platformio.org/en/latest/boards/espressif32/freenove_esp32_s3_wroom.html#board-espressif32-freenove-esp32-s3-wroom
platform = espressif32 @ 6.10.0
board = esp32-s3-devkitc-1 ;freenove_esp32_s3_wroom
framework = arduino
lib_deps =
    me-no-dev/AsyncTCP@^1.1.1
    bblanchon/ArduinoJson@7.1.0
    https://github.com/me-no-dev/ESPAsyncWebServer.git#7f3753454b1f176c4b6d6bcd1587a135d95ca63c
    https://github.com/ElectronicCats/mpu6050.git#v1.3.1
    nanopb/Nanopb@0.4.9

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=0
build_src_filter =
    +<*>
    -<read_serial.cpp>
extra_scripts = pre:build_revision.py

;/dev/ttyCH343USB0
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
; monitor_rts = 0
; monitor_dtr = 0
