/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SBR_RECORDING_RECORDING_PB_H_INCLUDED
#define PB_SBR_RECORDING_RECORDING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _sbr_recording_RecordingSample_ControlMode {
    sbr_recording_RecordingSample_ControlMode_AUTO = 0,
    sbr_recording_RecordingSample_ControlMode_MANUAL = 1,
    sbr_recording_RecordingSample_ControlMode_FUNCTION = 2
} sbr_recording_RecordingSample_ControlMode;

/* Struct definitions */
/* SBRPB1 file: eight bytes "SBRPB1\0\0", then a varint-length-delimited
 RecordingHeader, followed by varint-length-delimited RecordingBatch messages.
 Batches are ordered, contiguous, and together contain record_count samples. */
typedef struct _sbr_recording_RecordingHeader {
    uint32_t format_version; /* Must be 1 for SBRPB1. */
    uint32_t sample_rate_hz; /* Nominal rate; use sample elapsed_us for timing. */
    uint32_t record_count;
    uint32_t capacity;
    float pid_kp;
    float pid_ki;
    float pid_kd;
    float pitch_setpoint_rad;
    float pitch_error_min_rad;
    float pitch_error_max_rad;
    uint32_t duty_cycle_min;
    uint32_t duty_cycle_max;
} sbr_recording_RecordingHeader;

typedef struct _sbr_recording_RecordingSample {
    uint32_t elapsed_us; /* Monotonic time since recording start. */
    float pitch_rad;
    float gyro_rad_s;
    float pid_output;
    int32_t motor1_encoder_pulses;
    int32_t motor2_encoder_pulses;
    uint32_t control_interval_us;
    uint32_t motor1_pwm;
    uint32_t motor2_pwm;
    bool motor1_dir_pin;
    bool motor2_dir_pin;
    sbr_recording_RecordingSample_ControlMode mode;
    bool estimates_valid;
    bool motor1_forward_command;
    bool motor2_forward_command;
} sbr_recording_RecordingSample;

typedef struct _sbr_recording_RecordingBatch {
    uint32_t first_index; /* Zero-based index of samples[0]. */
    pb_size_t samples_count;
    sbr_recording_RecordingSample samples[16]; /* At most 16 in SBRPB1. */
} sbr_recording_RecordingBatch;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _sbr_recording_RecordingSample_ControlMode_MIN sbr_recording_RecordingSample_ControlMode_AUTO
#define _sbr_recording_RecordingSample_ControlMode_MAX sbr_recording_RecordingSample_ControlMode_FUNCTION
#define _sbr_recording_RecordingSample_ControlMode_ARRAYSIZE ((sbr_recording_RecordingSample_ControlMode)(sbr_recording_RecordingSample_ControlMode_FUNCTION+1))



#define sbr_recording_RecordingSample_mode_ENUMTYPE sbr_recording_RecordingSample_ControlMode


/* Initializer values for message structs */
#define sbr_recording_RecordingHeader_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define sbr_recording_RecordingBatch_init_default {0, 0, {sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default, sbr_recording_RecordingSample_init_default}}
#define sbr_recording_RecordingSample_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _sbr_recording_RecordingSample_ControlMode_MIN, 0, 0, 0}
#define sbr_recording_RecordingHeader_init_zero  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define sbr_recording_RecordingBatch_init_zero   {0, 0, {sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero, sbr_recording_RecordingSample_init_zero}}
#define sbr_recording_RecordingSample_init_zero  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _sbr_recording_RecordingSample_ControlMode_MIN, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define sbr_recording_RecordingHeader_format_version_tag 1
#define sbr_recording_RecordingHeader_sample_rate_hz_tag 2
#define sbr_recording_RecordingHeader_record_count_tag 3
#define sbr_recording_RecordingHeader_capacity_tag 4
#define sbr_recording_RecordingHeader_pid_kp_tag 5
#define sbr_recording_RecordingHeader_pid_ki_tag 6
#define sbr_recording_RecordingHeader_pid_kd_tag 7
#define sbr_recording_RecordingHeader_pitch_setpoint_rad_tag 8
#define sbr_recording_RecordingHeader_pitch_error_min_rad_tag 9
#define sbr_recording_RecordingHeader_pitch_error_max_rad_tag 10
#define sbr_recording_RecordingHeader_duty_cycle_min_tag 11
#define sbr_recording_RecordingHeader_duty_cycle_max_tag 12
#define sbr_recording_RecordingSample_elapsed_us_tag 1
#define sbr_recording_RecordingSample_pitch_rad_tag 2
#define sbr_recording_RecordingSample_gyro_rad_s_tag 3
#define sbr_recording_RecordingSample_pid_output_tag 4
#define sbr_recording_RecordingSample_motor1_encoder_pulses_tag 5
#define sbr_recording_RecordingSample_motor2_encoder_pulses_tag 6
#define sbr_recording_RecordingSample_control_interval_us_tag 7
#define sbr_recording_RecordingSample_motor1_pwm_tag 8
#define sbr_recording_RecordingSample_motor2_pwm_tag 9
#define sbr_recording_RecordingSample_motor1_dir_pin_tag 10
#define sbr_recording_RecordingSample_motor2_dir_pin_tag 11
#define sbr_recording_RecordingSample_mode_tag   12
#define sbr_recording_RecordingSample_estimates_valid_tag 13
#define sbr_recording_RecordingSample_motor1_forward_command_tag 14
#define sbr_recording_RecordingSample_motor2_forward_command_tag 15
#define sbr_recording_RecordingBatch_first_index_tag 1
#define sbr_recording_RecordingBatch_samples_tag 2

/* Struct field encoding specification for nanopb */
#define sbr_recording_RecordingHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   format_version,    1) \
X(a, STATIC,   SINGULAR, UINT32,   sample_rate_hz,    2) \
X(a, STATIC,   SINGULAR, UINT32,   record_count,      3) \
X(a, STATIC,   SINGULAR, UINT32,   capacity,          4) \
X(a, STATIC,   SINGULAR, FLOAT,    pid_kp,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    pid_ki,            6) \
X(a, STATIC,   SINGULAR, FLOAT,    pid_kd,            7) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch_setpoint_rad,   8) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch_error_min_rad,   9) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch_error_max_rad,  10) \
X(a, STATIC,   SINGULAR, UINT32,   duty_cycle_min,   11) \
X(a, STATIC,   SINGULAR, UINT32,   duty_cycle_max,   12)
#define sbr_recording_RecordingHeader_CALLBACK NULL
#define sbr_recording_RecordingHeader_DEFAULT NULL

#define sbr_recording_RecordingBatch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   first_index,       1) \
X(a, STATIC,   REPEATED, MESSAGE,  samples,           2)
#define sbr_recording_RecordingBatch_CALLBACK NULL
#define sbr_recording_RecordingBatch_DEFAULT NULL
#define sbr_recording_RecordingBatch_samples_MSGTYPE sbr_recording_RecordingSample

#define sbr_recording_RecordingSample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   elapsed_us,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch_rad,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_rad_s,        3) \
X(a, STATIC,   SINGULAR, FLOAT,    pid_output,        4) \
X(a, STATIC,   SINGULAR, SINT32,   motor1_encoder_pulses,   5) \
X(a, STATIC,   SINGULAR, SINT32,   motor2_encoder_pulses,   6) \
X(a, STATIC,   SINGULAR, UINT32,   control_interval_us,   7) \
X(a, STATIC,   SINGULAR, UINT32,   motor1_pwm,        8) \
X(a, STATIC,   SINGULAR, UINT32,   motor2_pwm,        9) \
X(a, STATIC,   SINGULAR, BOOL,     motor1_dir_pin,   10) \
X(a, STATIC,   SINGULAR, BOOL,     motor2_dir_pin,   11) \
X(a, STATIC,   SINGULAR, UENUM,    mode,             12) \
X(a, STATIC,   SINGULAR, BOOL,     estimates_valid,  13) \
X(a, STATIC,   SINGULAR, BOOL,     motor1_forward_command,  14) \
X(a, STATIC,   SINGULAR, BOOL,     motor2_forward_command,  15)
#define sbr_recording_RecordingSample_CALLBACK NULL
#define sbr_recording_RecordingSample_DEFAULT NULL

extern const pb_msgdesc_t sbr_recording_RecordingHeader_msg;
extern const pb_msgdesc_t sbr_recording_RecordingBatch_msg;
extern const pb_msgdesc_t sbr_recording_RecordingSample_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sbr_recording_RecordingHeader_fields &sbr_recording_RecordingHeader_msg
#define sbr_recording_RecordingBatch_fields &sbr_recording_RecordingBatch_msg
#define sbr_recording_RecordingSample_fields &sbr_recording_RecordingSample_msg

/* Maximum encoded size of messages (where known) */
#define SBR_RECORDING_RECORDING_PB_H_MAX_SIZE    sbr_recording_RecordingBatch_size
#define sbr_recording_RecordingBatch_size        1046
#define sbr_recording_RecordingHeader_size       66
#define sbr_recording_RecordingSample_size       63

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
