/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "recording.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sbr_recording_RecordingHeader, sbr_recording_RecordingHeader, AUTO)


PB_BIND(sbr_recording_RecordingSettings, sbr_recording_RecordingSettings, AUTO)


PB_BIND(sbr_recording_RecordingBatch, sbr_recording_RecordingBatch, 2)


PB_BIND(sbr_recording_RecordingSample, sbr_recording_RecordingSample, AUTO)





